# Generated by Django 5.1.7 on 2025-03-26 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, max_length=150, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('email_adresse', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('secteur_activite', models.CharField(max_length=255, null=True, verbose_name="Secteur d'activité")),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coopérative',
                'verbose_name_plural': 'Coopératives',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='nom', max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=150, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(max_length=255)),
                ('numero_identification', models.CharField(max_length=6, unique=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='cooperative.cooperative')),
            ],
        ),
    ]
