# Generated by Django 5.1.7 on 2025-04-01 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0002_membre_user_alter_membre_nom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ['-date_inscription']},
        ),
        migrations.AddField(
            model_name='membre',
            name='date_inscription',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 4, 1, 9, 48, 18, 330792)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='email_adresse',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='membre',
            name='status',
            field=models.CharField(choices=[('en attente', 'En attente'), ('actif', 'Membre Actif'), ('inactif', 'Membre Inactif')], default='en attente', max_length=20),
        ),
    ]
