# Generated by Django 5.1.7 on 2025-04-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0003_alter_membre_options_membre_date_inscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
