# Generated by Django 5.1.7 on 2025-04-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooperative', '0004_membre_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='status',
        ),
    ]
